# Generated by Django 4.1.7 on 2023-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=60, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='upload_to')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('password_reset_code', models.CharField(blank=True, max_length=120, null=True)),
                ('reset_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('activation_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'MyUser',
                'verbose_name_plural': 'MyUser',
                'ordering': ['-timestamp'],
            },
        ),
    ]
