# Generated by Django 4.1.7 on 2023-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_persentage',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (65, '65'), (70, '70'), (75, '75'), (80, '80'), (85, '85'), (90, '90'), (95, '95'), (100, '100')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='in_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=False),
        ),
    ]
