# Generated by Django 4.1.7 on 2023-03-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'discount_price'], 'verbose_name': 'Mehsullar', 'verbose_name_plural': 'Mehsul'},
        ),
    ]
