# Generated by Django 4.1.7 on 2023-03-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_created_at_alter_category_uptated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kateqoriyalar', 'verbose_name_plural': 'Kateqoriya'},
        ),
    ]
