# Generated by Django 4.1.7 on 2023-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'discount_price'], 'verbose_name': 'Mehsullar', 'verbose_name_plural': 'Mehsullar'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Məhsul şəkilləri', 'verbose_name_plural': 'Məhsulların şəkilləri'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kateqoriya'),
        ),
    ]
